### ISSUE TITLE
Option to store _class or not

### ISSUE THREAD

**Issue by dlangford** [al6x/mongodb#1]
I'm looking into using your mongodb_model gem and found that it stores the class name in a "_class" field. I traced it back to this gem. What are your thoughts on making this field optional, similar to the :generate_id option? In my project, I have no use for it, and it just takes up space. Or am I missing something?

**Comment by al6x** [comment]
If You are using mongodb gem as just a low-level MongoDB driver, with hash only - it shouldn't add `_class` attribute.
But, if You are using Objects or Models as a Documents - there's a problem - if You load a Model from database - how do You know which Ruby-class corresponds to this document and should be instantiated?

In Rails ActiveRecord it's soved by having strong correspondence between database table names and model names (class names). So You can infer class name from table name. But it has disadvantages - Your persistence logic is not flexible it's tightly coupled with naming of Models and Tables.

There's also another approach - You can store any object in any collection (or use only one collection at all and store all models there). 
But to do so You need to store an information about the model class in every document.

So, having a `_class` to be stored with every model-document is important.
Yes it costs some extra space, but instead gives You flexibility.

**Comment by dlangford** [comment]
Thanks for your response, Alexey. Yes, I was thinking more about how ActiveRecord does it (even though I don't use Rails), where Models:Tables = 1:1. I can definitely see the advantages of storing the class name in the MongoDB collection, now. But, for me at least, this presents a problem in that I have existing data that does not have the class name field. Furthermore, if my class is in some Module (for name-spacing), the class name get get lengthy. I'm just suggesting that you give developers the _option_ to store the class name, or not, depending on the application design. But I realize that may not be possible depending on how the gem has been architected (I have not delved too deep into the source). For example, in checking out MongoMapper, it seems that it does not store class name unless your model class is inherited from another (I could be wrong?).

I did not realize that the low-level driver (this gem) did not store class. I was checking out the model-based approach (mongo_model gem). I'll take a closer look at the low-level driver. I'm used to using the Ruby MongoDB driver anyway, and this gem seems to have some nice helpers that make accessing collection more object-like.

Should I go ahead an close this "issue", then?

**Comment by al6x** [comment]
Yes, I believe we can close it.
As about efficiency -  yes, maybe it makes sense to use just driver and hashes and not models
